version: "3.9"
services:
  server:
    build:
      context: .
      dockerfile: ./build/Dockerfile.server.dev
    environment:
      POSTGRES_HOST: db
      REDIS_URL: redis://redis:6379
      NODE_APP_INSTANCE: 0
    ports:
      - 4000:4000
    volumes:
      - ./server:/opt/app/server
    depends_on:
      - db
      - db_migrations
      - redis
  db_migrations:
    build:
      context: .
      dockerfile: ./build/Dockerfile.server.dev
    environment:
      POSTGRES_HOST: db
    depends_on:
      - db
    command: "yarn server knex migrate:latest --knexfile src/knexfile.ts"
  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - "db_data:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 15s
      timeout: 5s
      retries: 5
  redis:
    image: redis:alpine
    ports:
      - 6378:6379
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 1s
      timeout: 3s
      retries: 30
volumes:
  db_data:
